# Generated by Django 4.0.3 on 2022-04-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about_me',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
