# Generated by Django 4.0.3 on 2022-04-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_about_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='jop_title',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
