# Generated by Django 2.2.7 on 2022-04-09 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('subject', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='static/blog/images')),
                ('create_at', models.TimeField(auto_now=True)),
            ],
        ),
    ]
