# Generated by Django 4.0.3 on 2022-04-11 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_create_at_alter_post_create_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-create_at']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-create_at']},
        ),
    ]
