# Generated by Django 4.0.3 on 2022-05-12 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('illnesses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='illnesses',
            old_name='description',
            new_name='Symptoms',
        ),
        migrations.RenameField(
            model_name='illnesses',
            old_name='subject',
            new_name='diagnosis',
        ),
        migrations.RenameField(
            model_name='illnesses',
            old_name='title',
            new_name='illness_name',
        ),
    ]
