# Generated by Django 4.0.3 on 2022-05-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('illnesses', '0002_rename_description_illnesses_symptoms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='illnesses',
            name='Symptoms',
            field=models.TextField(),
        ),
    ]
