# Generated by Django 4.0.3 on 2022-05-17 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('illnesses', '0003_alter_illnesses_symptoms'),
    ]

    operations = [
        migrations.AddField(
            model_name='illnesses',
            name='about_illness',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='illnesses',
            name='protection',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
