# Generated by Django 4.0.5 on 2022-06-02 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('illnesses', '0006_alter_illnesses_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='illnesses_ar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('illness_name', models.CharField(max_length=100)),
                ('about_illness', models.CharField(max_length=1000)),
                ('protection', models.TextField()),
                ('Symptoms', models.TextField()),
                ('diagnosis', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='static/illnesses/images')),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='illnesses_ow', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-create_at'],
            },
        ),
    ]
