# Generated by Django 4.0.3 on 2022-04-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='advice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/advice')),
                ('title', models.TextField()),
                ('create_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-create_at'],
            },
        ),
    ]
