# Generated by Django 4.0.3 on 2022-05-10 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_aid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advice',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advice',
            name='title',
            field=models.CharField(max_length=400),
        ),
    ]
