# Generated by Django 2.2.7 on 2022-06-01 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_aid', '0002_advice_description_alter_advice_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advice',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
