# Generated by Django 4.0.5 on 2022-06-02 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_aid', '0003_auto_20220601_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advice',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
