# Generated by Django 4.0.5 on 2022-06-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_aid', '0004_alter_advice_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='advice_ar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/advice')),
                ('title', models.CharField(max_length=400)),
                ('description', models.TextField()),
                ('create_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-create_at'],
            },
        ),
    ]
