# Generated by Django 4.0.3 on 2022-04-09 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_book_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='link',
        ),
    ]
