# Generated by Django 4.0.3 on 2022-04-11 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_alter_doctor_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['-create_at']},
        ),
        migrations.AddField(
            model_name='doctor',
            name='create_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
