# Generated by Django 4.0.5 on 2022-06-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_alter_doctor_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor_ar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Specialization', models.CharField(max_length=1000)),
                ('address', models.CharField(max_length=1000)),
                ('phone', models.CharField(max_length=12)),
                ('image', models.ImageField(blank=True, upload_to='static/images')),
                ('create_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-create_at'],
            },
        ),
    ]
